"""
Run taxonomy discovery over the cleaned corpus.

Run:
    python scripts/02_discover_taxonomy.py

Reads  : data/interim/reviews_clean.parquet   (read-only)
         config/taxonomy.yaml
Writes : reports/taxonomy_discovery.md
         data/processed/taxonomy_discovery_areas.csv
         data/processed/taxonomy_discovery_cooccurrence.csv

The cleaned dataset is never modified. Every figure quoted in
docs/TAXONOMY.md comes from a run of this script.
"""

from __future__ import annotations

import _bootstrap  # noqa: F401  -- must precede project imports
import argparse
import logging
import sys

import pandas as pd

from config.settings import Paths, get_settings
from voc.discovery import analyse, to_dataframe, top_cooccurring_pairs
from voc.taxonomy import get_taxonomy


def _table(headers: list[str], rows: list[list[str]]) -> str:
    head = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join("---" for _ in headers) + " |"
    body = "\n".join("| " + " | ".join(cells) + " |" for cells in rows)
    return "\n".join([head, sep, body])


def build_report(result, taxonomy, frame: pd.DataFrame) -> str:
    platforms = sorted(frame["platform"].astype(str).unique())
    parts: list[str] = []

    parts.append("# Taxonomy Discovery — Estimates\n")
    parts.append(
        "> Generated by `scripts/02_discover_taxonomy.py` from "
        "`data/interim/reviews_clean.parquet`.\n>\n"
        "> **These are discovery estimates, not classifications.** Every number "
        "below comes from keyword/phrase probes defined in `config/taxonomy.yaml`. "
        "Probes are high-precision and mediocre-recall by design, so treat every "
        "share as a **lower bound**. Phase 3 replaces them with LLM classification "
        "validated against a hand-labelled gold set.\n"
    )
    parts.append(
        f"\nCorpus: **{result.n_reviews:,} reviews** · taxonomy version "
        f"**{taxonomy.version}** · **{len(taxonomy.product_areas)} product areas** "
        f"across {len(taxonomy.domains)} domains.\n"
    )

    # --- multi-label evidence ---------------------------------------------
    parts.append("\n## Reviews are multi-label\n")
    dist = result.areas_per_review_dist
    parts.append(
        _table(
            ["Areas matched", *[str(k) for k in sorted(dist)]],
            [["Reviews", *[f"{dist[k]:,}" for k in sorted(dist)]]],
        )
    )
    single = dist.get(1, 0)
    parts.append(
        f"\nMean **{result.mean_areas_per_review:.2f}** areas per review; only "
        f"**{single:,} ({single / result.n_reviews * 100:.1f}%)** touch exactly one. "
        "Single-label classification would be factually wrong on this corpus.\n"
    )

    # --- area sizing -------------------------------------------------------
    parts.append("\n## Area sizing\n")
    rows = []
    for area in sorted(result.areas, key=lambda a: a.share_pct, reverse=True):
        rows.append(
            [
                f"`{area.area_id}`",
                area.domain,
                f"{area.matched:,}",
                f"{area.share_pct:.1f}%",
                f"{area.share_negative_pct:.1f}%",
                f"{area.share_positive_pct:.1f}%",
                f"{area.positive_negative_ratio:.2f}×",
            ]
        )
    parts.append(
        _table(
            ["Area", "Domain", "Matched", "% corpus", "% of neg", "% of pos", "pos:neg"],
            rows,
        )
    )
    parts.append(
        "\n**Reading `pos:neg`.** Above 1.0 the area attracts more praise than "
        "complaint relative to base rates — a product *strength*. Below ~0.3 the "
        "area is a failure-only surface: customers essentially never praise it. "
        "This split is why issue types and strength types are modelled separately "
        "instead of as one signed sentiment axis.\n"
    )

    # --- platform discrimination ------------------------------------------
    parts.append("\n## Platform discrimination\n")
    parts.append(
        "Spread = highest platform share ÷ lowest. High spread means the area "
        "carries competitive signal that a merged parent category would hide.\n"
    )
    rows = []
    for area in sorted(result.areas, key=lambda a: a.platform_spread, reverse=True):
        rows.append(
            [
                f"`{area.area_id}`",
                *[f"{area.platform_share_pct.get(p, 0):.1f}%" for p in platforms],
                f"**{area.platform_spread:.1f}×**",
            ]
        )
    parts.append(_table(["Area", *platforms, "Spread"], rows))

    # --- support as downstream signal -------------------------------------
    parts.append("\n## Customer support is downstream\n")
    parts.append(
        f"Base rate: **{result.support_base_rate * 100:.1f}%** of reviews mention support. "
        "Lift = P(support mentioned | area) ÷ base rate.\n"
    )
    rows = []
    ranked = sorted(
        (a for a in result.areas if a.area_id != result.support_area_id),
        key=lambda a: a.support_lift,
        reverse=True,
    )
    for area in ranked:
        rows.append(
            [
                f"`{area.area_id}`",
                f"{result.support_base_rate * area.support_lift * 100:.1f}%",
                f"{area.support_lift:.2f}×",
            ]
        )
    parts.append(_table(["Area", "P(support | area)", "Lift"], rows))
    parts.append(
        "\nOperational failures pull support contact well above base rate while "
        "value-perception areas push it below. Support is a **failure amplifier**, "
        "not an independent driver — which is why `support_escalation` is modelled "
        f"as a review-level attribute in addition to `{result.support_area_id}` "
        "existing as an area for cases where support itself is the problem.\n"
    )

    # --- overlap -----------------------------------------------------------
    parts.append("\n## Area overlap (merge check)\n")
    parts.append(
        "Jaccard overlap between area pairs. Uniformly low values are evidence "
        "the areas are distinct surfaces rather than synonyms of each other.\n"
    )
    rows = [
        [f"`{a}`", f"`{b}`", f"{j:.3f}"]
        for a, b, j in top_cooccurring_pairs(result, limit=12)
    ]
    parts.append(_table(["Area A", "Area B", "Jaccard"], rows))

    # --- robustness --------------------------------------------------------
    parts.append("\n## Robustness checks\n")
    worst = max(result.areas, key=lambda a: abs(a.near_dup_inflation_pp))
    parts.append(
        f"**Near-duplicate inflation.** Comparing all rows against "
        f"representative-only rows, the largest shift in any area share is "
        f"**{abs(worst.near_dup_inflation_pp):.2f} pp** (`{worst.area_id}`). "
        "Templated reviews are not driving the taxonomy.\n"
    )
    parts.append(
        f"\n**Unmatched residual.** **{result.unmatched:,} reviews "
        f"({result.unmatched_pct:.1f}%)** match no area probe, with a mean rating of "
        f"**{result.unmatched_mean_rating:.2f}** vs **{result.corpus_mean_rating:.2f}** "
        "for the corpus. The residual skews short and positive. Manual reading "
        "found it dominated by generic sentiment (\"worst app ever\") and by "
        "lexical recall misses (\"received one item less\" is fulfilment but "
        "matches no probe) — not by a missing category. This is the main reason "
        "these estimates are floors.\n"
    )

    parts.append("\n## Caveats carried from Phase 1\n")
    for key, text in taxonomy.dataset_caveats.items():
        parts.append(f"- **{key.replace('_', ' ')}** — {text.strip()}\n")

    return "\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quiet", action="store_true", help="Suppress the console summary.")
    args = parser.parse_args()

    settings = get_settings()
    logging.basicConfig(level=settings.log_level, format="%(levelname)-8s %(name)s | %(message)s")
    log = logging.getLogger("discover")

    Paths.ensure_output_dirs()

    taxonomy = get_taxonomy()
    log.info(
        "Loaded taxonomy v%s: %d areas, %d domains, %d attributes",
        taxonomy.version,
        len(taxonomy.product_areas),
        len(taxonomy.domains),
        len(taxonomy.attributes),
    )

    if not Paths.clean_reviews.exists():
        log.error("Cleaned dataset not found. Run: python scripts/01_build_clean.py")
        return 1

    frame = pd.read_parquet(Paths.clean_reviews)
    frame["platform"] = frame["platform"].astype(str)
    log.info("Loaded %d cleaned reviews", len(frame))

    result = analyse(frame, taxonomy)

    areas_frame = to_dataframe(result)
    areas_frame.to_csv(Paths.taxonomy_discovery_areas, index=False)
    result.cooccurrence.round(4).to_csv(Paths.taxonomy_discovery_matrix)
    Paths.taxonomy_discovery_report.write_text(
        build_report(result, taxonomy, frame), encoding="utf-8"
    )

    if not args.quiet:
        print()
        print("=" * 78)
        print("  TAXONOMY DISCOVERY  (estimates from keyword probes, NOT classifications)")
        print("=" * 78)
        print(f"  Taxonomy version : {taxonomy.version}  ({len(taxonomy.product_areas)} areas)")
        print(f"  Reviews analysed : {result.n_reviews:,}")
        print(f"  Areas per review : {result.mean_areas_per_review:.2f} mean")
        print(f"  Unmatched        : {result.unmatched:,} ({result.unmatched_pct:.1f}%)")
        print("-" * 78)
        print(f"  {'area':30s}{'%corpus':>9s}{'pos:neg':>9s}{'spread':>8s}{'supp lift':>11s}")
        for area in sorted(result.areas, key=lambda a: a.share_pct, reverse=True):
            # Support's lift against itself is 1/base_rate and carries no meaning.
            lift = "     --" if area.area_id == result.support_area_id else f"{area.support_lift:>6.2f}x"
            print(
                f"  {area.area_id:30s}{area.share_pct:>8.1f}%"
                f"{area.positive_negative_ratio:>8.2f}x{area.platform_spread:>7.1f}x"
                f"{lift:>10s}"
            )
        print("-" * 78)
        print(f"  Report : {Paths.taxonomy_discovery_report}")
        print(f"  Areas  : {Paths.taxonomy_discovery_areas}")
        print(f"  Matrix : {Paths.taxonomy_discovery_matrix}")
        print("=" * 78)
        print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
