"""
Run exploratory data analysis over the cleaned corpus.

Run:
    python scripts/03_run_eda.py

Reads  : data/interim/reviews_clean.parquet   (read-only)
         data/interim/cleaning_report.json    (for reconciliation)
         config/taxonomy.yaml
Writes : reports/EDA_REPORT.md
         reports/figures/*.png

No LLM is used. Everything here is deterministic and reproducible.
The cleaned dataset is never modified.
"""

from __future__ import annotations

import _bootstrap  # noqa: F401  -- must precede project imports
import argparse
import json
import logging
import sys

import pandas as pd

from config.settings import Paths, get_settings
from voc.eda import MIN_REVIEWS_FOR_COMPARISON, run_eda
from voc.plots import generate_all
from voc.taxonomy import get_taxonomy


def _table(headers: list[str], rows: list[list[str]]) -> str:
    head = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join("---" for _ in headers) + " |"
    body = "\n".join("| " + " | ".join(cells) + " |" for cells in rows)
    return "\n".join([head, sep, body])


def build_report(result, frame: pd.DataFrame, figures: list) -> str:
    profile = result.profile
    temporal = result.temporal
    ratings = result.ratings
    text = result.text
    themes = result.themes
    parts: list[str] = []

    def figure(name: str, caption: str) -> str:
        return f"\n![{caption}](figures/{name})\n\n*{caption}*\n"

    # ------------------------------------------------------------------ intro
    parts.append("# Exploratory Data Analysis\n")
    parts.append(
        "> Generated by `scripts/03_run_eda.py` from `data/interim/reviews_clean.parquet`. "
        "Fully reproducible, no LLM involved. Re-run after any pipeline change.\n"
    )
    parts.append(
        "\n> **The distinction this whole report rests on.** Review volume in this dataset "
        "reflects **when reviews were collected**, not when customers had experiences. "
        "Every temporal and comparative figure below reports normalised shares, and raw "
        "volume is never treated as a demand signal.\n"
    )

    # -------------------------------------------------------------- 1 profile
    parts.append("\n## 1. Dataset profile\n")
    parts.append(
        _table(
            ["Metric", "Value"],
            [
                ["Total reviews", f"**{profile.total_reviews:,}**"],
                ["Platforms", ", ".join(f"{k} ({v:,})" for k, v in profile.by_platform.items())],
                ["Mean rating", f"{profile.mean_rating:.2f} ★"],
                ["Date range", f"{profile.date_min} → {profile.date_max} ({profile.span_days:,} days)"],
                ["Negative (1–2★)", f"{profile.rating_bucket_share.get('negative', 0):.1f}%"],
                ["Neutral (3★)", f"{profile.rating_bucket_share.get('neutral', 0):.1f}%"],
                ["Positive (4–5★)", f"{profile.rating_bucket_share.get('positive', 0):.1f}%"],
                ["Truncated at scraper cap", f"{profile.truncated:,} ({profile.truncated_pct:.1f}%)"],
                ["Near-duplicate groups", f"{profile.near_dup_groups} covering {profile.near_dup_members} reviews"],
                ["Non-Latin script", f"{profile.non_latin}"],
                ["Median length", f"{profile.char_len_stats['median']:.0f} chars / {profile.word_count_stats['median']:.0f} words"],
            ],
        )
    )

    parts.append("\n### Rating distribution\n")
    parts.append(
        _table(
            ["Rating", "Reviews", "Share"],
            [
                [f"{rating}★", f"{count:,}", f"{count / profile.total_reviews * 100:.1f}%"]
                for rating, count in profile.by_rating.items()
            ],
        )
    )
    parts.append(figure("01_rating_distribution.png", "Rating distribution across the corpus"))
    parts.append(figure("02_platform_distribution.png", "Review volume by platform"))

    # ------------------------------------------------------------- 2 temporal
    parts.append("\n## 2. Temporal analysis\n")
    parts.append(
        "**Volume by month is a sampling pattern.** It rises from double digits to "
        f"{int(temporal.monthly_volume['total'].max()):,} in the final month. That is the shape "
        "of the scrape, not a demand curve, and it must never be presented as growth.\n"
    )
    parts.append(figure("03_monthly_volume.png", "Monthly review volume by platform"))

    parts.append("\n### Platform date coverage\n")
    parts.append(
        _table(
            ["Platform", "First review", "Last review"],
            [[p, str(lo), str(hi)] for p, (lo, hi) in sorted(temporal.platform_date_ranges.items())],
        )
    )
    parts.append(
        f"\n**December 2024 alone is {temporal.december_share_pct:.1f}% of the corpus.** "
        "Coverage is not just thin early on — it is unevenly thin *per platform*, which is "
        "what makes naive cross-platform comparison unsafe.\n"
    )
    parts.append(figure("04_platform_coverage.png", "Platform coverage by month, with the valid comparison window boxed"))

    parts.append("\n### Recommended comparison window\n")
    if temporal.comparison_window:
        start, end = temporal.comparison_window
        parts.append(
            f"> **{start} → {end}** — {temporal.comparison_window_reviews:,} reviews "
            f"({temporal.comparison_window_pct:.1f}% of the corpus)\n"
        )
    else:
        parts.append("> **No defensible window exists.**\n")
    parts.append(f"\n{temporal.window_rationale}\n")
    parts.append(
        f"\nSelection rule: a month qualifies only when *every* platform has at least "
        f"**{MIN_REVIEWS_FOR_COMPARISON}** reviews in it. Below that, one templated complaint "
        "can move a share by several points.\n"
    )

    parts.append("\n### Sampling composition drifts over time\n")
    parts.append(
        _table(
            ["Month", "Reviews", "% negative"],
            [
                [str(month), f"{int(row['reviews']):,}", f"{row['negative_share_pct']:.1f}%"]
                for month, row in temporal.monthly_negative_share.iterrows()
            ],
        )
    )
    parts.append(
        "\nThe negative share of what was collected moves substantially month to month. "
        "**Complaint counts per month are therefore uninterpretable** — a rise could be more "
        "scraping, a more negative scrape, or genuinely worse service, and the data cannot "
        "distinguish them. Phase 5 trend analysis must use share-of-month, never counts.\n"
    )
    parts.append(figure("08_sampling_composition.png", "Collection volume against negative share by month"))

    # --------------------------------------------------------------- 3 rating
    parts.append("\n## 3. Rating analysis\n")
    by_platform = ratings.by_platform
    parts.append(
        _table(
            ["Platform", "Reviews", "Mean", "% negative", "% neutral", "% positive"],
            [
                [
                    str(platform), f"{int(row['reviews']):,}", f"{row['mean_rating']:.2f}",
                    f"{row['pct_negative']:.1f}%", f"{row['pct_neutral']:.1f}%", f"{row['pct_positive']:.1f}%",
                ]
                for platform, row in by_platform.iterrows()
            ],
        )
    )
    parts.append(figure("05_rating_by_platform.png", "Rating mix by platform"))

    parts.append("\n### Is the rating gap a sampling artefact?\n")
    parts.append(
        "Restricting to the comparison window equalises date coverage. If a platform's rating "
        "advantage were purely an artefact of *when* it was scraped, it would move here.\n"
    )
    parts.append(
        _table(
            ["Platform", "Mean (full)", "n (full)", "Mean (window)", "n (window)", "Shift"],
            [
                [
                    str(platform), f"{row['mean_rating_full']:.2f}", f"{int(row['n_full']):,}",
                    f"{row['mean_rating_window']:.2f}", f"{int(row['n_window']):,}",
                    f"{row['shift']:+.2f}",
                ]
                for platform, row in ratings.full_vs_window.iterrows()
            ],
        )
    )
    parts.append(f"\n{ratings.confound_note}\n")
    parts.append(figure("07_rating_over_time.png", "Mean rating over time by platform"))

    # ----------------------------------------------------------------- 4 text
    parts.append("\n## 4. Review text analysis\n")
    parts.append(
        _table(
            ["Platform", "Median chars", "Mean chars", "Median words", "% truncated"],
            [
                [
                    str(platform), f"{row['median_chars']:.0f}", f"{row['mean_chars']:.0f}",
                    f"{row['median_words']:.0f}", f"{row['pct_truncated']:.1f}%",
                ]
                for platform, row in text.length_by_platform.iterrows()
            ],
        )
    )
    parts.append(figure("06_review_length.png", "Review length distribution and per-platform spread"))

    comparison = text.truncated_comparison
    parts.append("\n### Truncation bias\n")
    parts.append(
        _table(
            ["Group", "Reviews", "Mean rating", "% negative"],
            [
                ["Truncated", f"{int(comparison['truncated_n']):,}",
                 f"{comparison['truncated_mean_rating']:.2f}", f"{comparison['truncated_pct_negative']:.1f}%"],
                ["Intact", f"{profile.total_reviews - int(comparison['truncated_n']):,}",
                 f"{comparison['intact_mean_rating']:.2f}", f"{comparison['intact_pct_negative']:.1f}%"],
            ],
        )
    )
    parts.append(
        "\nTruncated reviews are materially more negative. The plausible mechanism is that they "
        "are **cut before any resolution is described** — a review that ends \"...but support "
        "sorted it out\" loses its ending. Severity and resolution labels must be treated as "
        "lower-confidence on these rows.\n"
    )

    parts.append("\n### Most-mentioned terms (document frequency)\n")
    parts.append("Share of reviews containing the term, so one long rant cannot dominate.\n")
    negative_rows = [
        [term, f"{count:,}"] for term, count in text.top_terms_negative[:15]
    ]
    positive_rows = [
        [term, f"{count:,}"] for term, count in text.top_terms_positive[:15]
    ]
    parts.append("\n**In negative reviews (1–2★)**\n")
    parts.append(_table(["Term", "Reviews"], negative_rows))
    parts.append("\n**In positive reviews (4–5★)**\n")
    parts.append(_table(["Term", "Reviews"], positive_rows))
    parts.append(
        "\n> Keyword frequency is **exploratory only**. It cannot separate "
        "\"delivery was fast\" from \"delivery was late\", which is precisely why "
        "classification is an LLM job in Phase 3.\n"
    )

    parts.append("\n### Templated / boilerplate reviews\n")
    templates = text.template_groups.head(8)
    parts.append(
        _table(
            ["Group", "Reviews", "Platforms", "Mean ★", "Sample"],
            [
                [
                    str(group), str(int(row["members"])), str(row["platforms"]),
                    f"{row['mean_rating']:.1f}", f"`{row['sample']}…`",
                ]
                for group, row in templates.iterrows()
            ],
        )
    )
    parts.append(
        f"\n{profile.near_dup_members} reviews across {profile.near_dup_groups} groups are "
        "near-identical. The largest group differs only in a rupee amount. These are flagged, "
        "not deleted — deleting them would change the denominator of every percentage in this "
        "report — and pain-point counts downstream are reported both raw and "
        "representative-only.\n"
    )

    # --------------------------------------------------------------- 5 themes
    parts.append("\n## 5. Product-area exploration\n")
    parts.append(
        "> **Estimates, not classifications.** Shares come from keyword probes in "
        "`config/taxonomy.yaml` — high precision, mediocre recall, so **every number is a "
        "lower bound**. Nothing downstream treats these as labels. Full derivation and the "
        "taxonomy rationale: [`docs/TAXONOMY.md`](../docs/TAXONOMY.md).\n"
    )
    window = themes.share_window
    platforms = [c for c in window.columns if c != "all"]
    parts.append(
        _table(
            ["Product area", *platforms, "All", "Spread"],
            [
                [
                    f"`{area}`",
                    *[f"{window.loc[area, p]:.1f}%" for p in platforms],
                    f"**{window.loc[area, 'all']:.1f}%**",
                    f"{window.loc[area, platforms].max() / max(window.loc[area, platforms].min(), 0.1):.1f}×",
                ]
                for area in window.sort_values("all", ascending=False).index
            ],
        )
    )
    parts.append(figure("09_theme_comparison.png", "Exploratory theme shares by platform, comparison window only"))

    parts.append("\n### Shared vs platform-specific themes\n")
    parts.append(
        f"**Common to all platforms** (spread < 1.5×): "
        f"{', '.join(f'`{t}`' for t in themes.shared_themes) or '—'}\n"
    )
    for platform, areas in themes.platform_specific.items():
        if areas:
            parts.append(f"\n**Elevated on {platform}** (spread ≥ 2×): {', '.join(f'`{a}`' for a in areas)}\n")

    parts.append("\n### Does equalising the date window change the picture?\n")
    shift = themes.window_vs_full_shift
    largest = shift.abs().max().max()
    parts.append(
        f"Largest movement in any area/platform share when restricted to the comparison "
        f"window: **{largest:.1f} percentage points**. The platform signatures are therefore "
        "not an artefact of differing date coverage.\n"
    )

    # -------------------------------------------------------- 6 reconciliation
    parts.append("\n## 6. Validation\n")
    checks = result.reconciliation
    parts.append(
        _table(
            ["Check", "Result"],
            [
                ["Row count matches Phase 1", f"{'PASS' if checks['row_count_matches'] else 'FAIL'} ({checks['rows_found']:,} / {checks['rows_expected']:,})"],
                ["Platform counts reconcile", "PASS" if checks["platform_counts_match"] else "FAIL"],
                ["Rating counts reconcile", "PASS" if checks["rating_counts_match"] else "FAIL"],
                ["No nulls introduced", f"{'PASS' if checks['no_nulls'] else 'FAIL'} ({checks['null_cells']} null cells)"],
                ["Review IDs unique", "PASS" if checks["review_ids_unique"] else "FAIL"],
                ["Dates valid and unchanged", "PASS" if checks["dates_valid"] else "FAIL"],
                ["Ratings within 1–5", "PASS" if checks["ratings_in_range"] else "FAIL"],
                ["Truncation count reconciles", "PASS" if checks["truncated_matches"] else "FAIL"],
            ],
        )
    )
    parts.append(f"\n**Overall: {'ALL CHECKS PASSED' if checks['all_passed'] else 'FAILURES PRESENT'}**\n")

    parts.append("\n---\n")
    parts.append(
        "\nProduct Intelligence Summary and Phase 3 recommendations: "
        "[`docs/EDA_FINDINGS.md`](../docs/EDA_FINDINGS.md).\n"
    )
    return "\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-figures", action="store_true", help="Skip figure rendering.")
    args = parser.parse_args()

    settings = get_settings()
    logging.basicConfig(level=settings.log_level, format="%(levelname)-8s %(name)s | %(message)s")
    # matplotlib emits an INFO line per categorical axis; that is one per figure
    # per axis and drowns the pipeline's own output.
    logging.getLogger("matplotlib").setLevel(logging.WARNING)
    log = logging.getLogger("eda")

    Paths.ensure_output_dirs()

    if not Paths.clean_reviews.exists():
        log.error("Cleaned dataset not found. Run: python scripts/01_build_clean.py")
        return 1

    frame = pd.read_parquet(Paths.clean_reviews)
    frame["platform"] = frame["platform"].astype(str)
    cleaning_report = json.loads(Paths.clean_report.read_text(encoding="utf-8"))
    taxonomy = get_taxonomy()
    log.info("Loaded %d reviews and taxonomy v%s", len(frame), taxonomy.version)

    result = run_eda(frame, taxonomy, cleaning_report)

    if not result.reconciliation["all_passed"]:
        log.error("Reconciliation against Phase 1 FAILED: %s", result.reconciliation)
        return 2
    log.info("Reconciliation against Phase 1: all checks passed")

    figures: list = []
    if not args.no_figures:
        figures = generate_all(frame, result, Paths.figures_dir)
        log.info("Rendered %d figures into %s", len(figures), Paths.figures_dir)

    Paths.eda_report.write_text(build_report(result, frame, figures), encoding="utf-8")

    window = result.temporal.comparison_window
    print()
    print("=" * 78)
    print("  EXPLORATORY DATA ANALYSIS COMPLETE")
    print("=" * 78)
    print(f"  Reviews analysed   : {result.profile.total_reviews:,}")
    print(f"  Mean rating        : {result.profile.mean_rating:.2f}  "
          f"({result.profile.rating_bucket_share.get('negative', 0):.1f}% negative)")
    print(f"  Date range         : {result.profile.date_min} -> {result.profile.date_max}")
    print(f"  December 2024      : {result.temporal.december_share_pct:.1f}% of corpus")
    if window:
        print(f"  Comparison window  : {window[0]} -> {window[1]}  "
              f"({result.temporal.comparison_window_reviews:,} reviews, "
              f"{result.temporal.comparison_window_pct:.1f}%)")
        print(f"  Qualifying months  : {', '.join(result.temporal.months_meeting_threshold)}")
    else:
        print("  Comparison window  : NONE -- cross-platform comparison unsupported")
    print(f"  Reconciliation     : {'ALL PASSED' if result.reconciliation['all_passed'] else 'FAILED'}")
    print("-" * 78)
    print(f"  Report  : {Paths.eda_report}")
    print(f"  Figures : {Paths.figures_dir}  ({len(figures)} rendered)")
    print("=" * 78)
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
