"""
Generate root-cause hypotheses for the top pain points, grounded in retrieved reviews.

This is the Phase 6 deliverable. It runs a LangGraph cycle per pain point:
retrieve evidence, ask for causes, check every citation, and retry with wider
evidence when the check fails.

Needs an API key for whichever model VOC_SYNTHESIS_MODEL selects. The registry
default is `opus`; if no Anthropic key is set, point it at an open model:

    # estimate cost and exit
    python scripts/08_root_cause.py --dry-run

    # top 10 pain points on an OpenRouter model
    VOC_SYNTHESIS_MODEL=llama70b python scripts/08_root_cause.py --top 10

    # one pain point, more evidence per request
    python scripts/08_root_cause.py --top 1 --evidence 16

Reads  : data/processed/pain_points.parquet   (run 06_discover_painpoints.py)
         data/processed/reviews_enriched.parquet
         data/processed/review_labels.parquet
         artifacts/reviews.faiss              (run 05_build_embeddings.py)
Writes : data/processed/root_causes.parquet
         reports/ROOT_CAUSES.md

Every run prints a cost estimate first and asks before spending money.
"""

from __future__ import annotations

import _bootstrap  # noqa: F401  -- must precede project imports
import argparse
import logging
import sys
from datetime import datetime, timezone

import pandas as pd

from config.settings import Paths, get_settings
from voc.graph import run_pain_point
from voc.llm import create_provider
from voc.providers import ProviderError
from voc.retrieval import Retriever
from voc.rootcause import DEFAULT_HYPOTHESES, MAX_OUTPUT_TOKENS, build_system_prompt

#: Rough input size per request: system prompt plus the evidence block.
APPROX_INPUT_TOKENS_PER_EVIDENCE = 70


def build_report(results: list, pain_points: pd.DataFrame, profile, settings) -> str:
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    grounded = [r for r in results if r.hypotheses]
    lines: list[str] = []
    add = lines.append

    add("# Root-Cause Hypotheses")
    add("")
    add(f"**{generated}** · {len(results)} pain points examined · "
        f"{sum(len(r.hypotheses) for r in results)} grounded hypotheses · "
        f"model `{profile.model_id}`")
    add("")
    add("Phase 4 ranked what hurts and Phase 5 showed where it is worse. This asks "
        "*why*, using only the reviews the retriever supplied for each pain point.")
    add("")
    add("---")
    add("")
    add("## These are hypotheses, not findings")
    add("")
    add("Every item below is a **candidate mechanism** generated by a language model "
        "from customer text. Customer reviews describe symptoms; they cannot "
        "establish causes. That is why each hypothesis carries a **proposed check** "
        "— the observation that would confirm or kill it. The check is the "
        "actionable output; the hypothesis is a reason to run it.")
    add("")
    add("**Every citation is verified.** A hypothesis may only cite review ids that "
        "were actually supplied to the model for that pain point. One citing "
        "anything else is rejected outright rather than repaired — stripping the "
        "bad id would leave a claim whose stated support does not exist, which "
        "reads as evidence-backed and is not.")
    add("")
    add("---")
    add("")

    for result in results:
        add(f"## `{result.product_area}` / `{result.issue_type}`")
        add("")
        match = pain_points[
            (pain_points["product_area"] == result.product_area)
            & (pain_points["issue_type"] == result.issue_type)
        ]
        if not match.empty:
            row = match.iloc[0]
            add(f"Rank {int(row['rank'])} · {int(row['volume']):,} reviews · "
                f"severity {row['mean_severity']:.2f} · "
                f"escalation {row['escalation_rate'] * 100:.0f}% · "
                f"score {row['score']:.3f}")
            add("")
        add(f"*Evidence supplied: {len(result.evidence_ids)} reviews.*")
        add("")

        if not result.hypotheses:
            add("**No grounded hypothesis survived validation.**")
            add("")
            for issue in result.issues:
                add(f"- `{issue.kind}` — {issue.detail}")
            add("")
            continue

        for n, item in enumerate(result.hypotheses, start=1):
            add(f"### {n}. {item.hypothesis}")
            add("")
            add(f"**Mechanism.** {item.mechanism}")
            add("")
            add(f"**Check this.** {item.proposed_check}")
            add("")
            if item.disconfirming_evidence.strip():
                add(f"**Against it.** {item.disconfirming_evidence}")
                add("")
            add(f"**Cited reviews.** {', '.join(f'`{i}`' for i in item.supporting_review_ids)}")
            add("")
            add(f"**Model confidence.** {item.confidence:.2f} — the model's own, "
                "not a measured probability.")
            add("")
        rejected = [i for i in result.issues if i.kind != "no_disconfirming_evidence"]
        if rejected:
            add("<details><summary>Rejected during validation</summary>")
            add("")
            for issue in rejected:
                add(f"- `{issue.kind}` — {issue.detail}")
            add("")
            add("</details>")
            add("")
        add("---")
        add("")

    add("## Caveats")
    add("")
    add("**A verified citation is not a verified cause.** The check confirms the "
        "model quoted reviews it was given. It says nothing about whether the "
        "mechanism is real.")
    add("")
    add("**Confidence is self-reported.** Phase 9's gold set is what would turn "
        "these into measured claims.")
    add("")
    add(f"**Retrieval is semantic and bounded.** Each pain point saw at most the "
        f"reviews the index ranked closest to it. A cause visible only in reviews "
        "outside that set cannot be proposed.")
    add("")
    add(f"**{len(results) - len(grounded)} of {len(results)} pain points produced "
        "nothing.** Where that happened it is reported above rather than omitted.")
    add("")
    return "\n".join(lines) + "\n"


def main() -> int:
    settings = get_settings()

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", type=int, default=10, help="Pain points to examine.")
    parser.add_argument("--evidence", type=int, default=8, help="Reviews retrieved per pain point.")
    parser.add_argument("--hypotheses", type=int, default=DEFAULT_HYPOTHESES,
                        help="Hypotheses requested per pain point.")
    parser.add_argument("--dry-run", action="store_true", help="Estimate cost and exit.")
    parser.add_argument("--yes", action="store_true", help="Skip the cost confirmation.")
    args = parser.parse_args()

    logging.basicConfig(level=settings.log_level, format="%(levelname)-8s %(name)s | %(message)s")
    log = logging.getLogger("rootcause")
    Paths.ensure_output_dirs()

    required = [Paths.pain_points, Paths.enriched_reviews, Paths.enriched_labels]
    for path in required:
        if not path.exists():
            log.error("%s not found. Run scripts/06_discover_painpoints.py first.", path.name)
            return 1
    if not Paths.faiss_index.exists():
        log.error("No FAISS index. Run: python scripts/05_build_embeddings.py")
        return 1

    pain_points = pd.read_parquet(Paths.pain_points).head(args.top)
    reviews = pd.read_parquet(Paths.enriched_reviews)
    labels = pd.read_parquet(Paths.enriched_labels)
    profile = settings.synthesis_profile

    requests = len(pain_points)
    input_tokens = requests * (
        len(build_system_prompt(args.hypotheses)) // 4
        + args.evidence * APPROX_INPUT_TOKENS_PER_EVIDENCE
    )
    output_tokens = requests * MAX_OUTPUT_TOKENS // 2
    estimate = profile.estimate_cost_usd(input_tokens, output_tokens)

    print()
    print("=" * 78)
    print("  ROOT-CAUSE HYPOTHESES")
    print("=" * 78)
    print(f"  Model        : {profile.display_name}  ({profile.model_id})")
    print(f"  Selected via : VOC_SYNTHESIS_MODEL={profile.key}")
    print(f"  Pain points  : {requests}")
    print(f"  Evidence     : {args.evidence} reviews each")
    print(f"  Hypotheses   : up to {args.hypotheses} each")
    print("-" * 78)
    print(f"  ESTIMATE     : ~{input_tokens:,} in / ~{output_tokens:,} out "
          f"-> ${estimate:,.2f}")
    print("=" * 78)
    print()

    if args.dry_run:
        log.info("Dry run - no API calls made.")
        return 0

    if not args.yes:
        try:
            if input("Proceed and spend this? [y/N] ").strip().lower() not in ("y", "yes"):
                print("Aborted.")
                return 0
        except EOFError:
            log.error("No TTY for confirmation. Re-run with --yes.")
            return 1

    try:
        provider = create_provider(profile, settings)
    except (RuntimeError, ProviderError) as exc:
        log.error("%s", exc)
        log.error("The registry default is `opus` (Anthropic). With only an "
                  "OpenRouter key set, run: VOC_SYNTHESIS_MODEL=llama70b python "
                  "scripts/08_root_cause.py")
        return 1

    retriever = Retriever.from_paths(
        Paths.faiss_index, reviews, settings.embedding_model, labels
    )

    results = []
    for index, row in enumerate(pain_points.itertuples(), start=1):
        print(f"    {index}/{requests}  {row.product_area}/{row.issue_type}", end="\r", flush=True)
        state = run_pain_point(
            row.product_area,
            row.issue_type,
            {
                "volume": int(row.volume),
                "mean_severity": float(row.mean_severity),
                "escalation_rate": float(row.escalation_rate),
                "churn_rate": float(row.churn_rate),
            },
            retriever,
            profile,
            provider,
            k=args.evidence,
            n=args.hypotheses,
        )
        if state.get("result") is not None:
            results.append(state["result"])
    print()

    rows = []
    for result in results:
        for item in result.hypotheses:
            rows.append(
                {
                    "product_area": result.product_area,
                    "issue_type": result.issue_type,
                    "hypothesis": item.hypothesis,
                    "mechanism": item.mechanism,
                    "proposed_check": item.proposed_check,
                    "disconfirming_evidence": item.disconfirming_evidence,
                    "supporting_review_ids": " ".join(item.supporting_review_ids),
                    "confidence": item.confidence,
                    "evidence_supplied": len(result.evidence_ids),
                }
            )
    if rows:
        pd.DataFrame(rows).to_parquet(Paths.root_causes, index=False)

    Paths.root_cause_report.write_text(
        build_report(results, pain_points, profile, settings), encoding="utf-8"
    )

    grounded = sum(1 for r in results if r.hypotheses)
    total_usage = {}
    for result in results:
        for key, value in result.usage.items():
            total_usage[key] = total_usage.get(key, 0) + value
    actual = profile.estimate_cost_usd(
        total_usage.get("input_tokens", 0), total_usage.get("output_tokens", 0)
    )
    issue_counts: dict[str, int] = {}
    for result in results:
        for issue in result.issues:
            issue_counts[issue.kind] = issue_counts.get(issue.kind, 0) + 1

    print("=" * 78)
    print("  COMPLETE")
    print("=" * 78)
    print(f"  Pain points with a grounded hypothesis : {grounded}/{len(results)}")
    print(f"  Hypotheses kept  : {len(rows)}")
    print(f"  Validation issues: {issue_counts or 'none'}")
    print(f"  Tokens           : {total_usage.get('input_tokens', 0):,} in / "
          f"{total_usage.get('output_tokens', 0):,} out  (~${actual:,.3f})")
    print("-" * 78)
    print(f"  Table  : {Paths.root_causes}")
    print(f"  Report : {Paths.root_cause_report}")
    print("=" * 78)
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
