"""
Layer 10 -- opportunity generation.

A pain point says something hurts. A root cause proposes why. An opportunity is
the bridge to work: a specific change, tied to the mechanism it addresses, with
the metric that would show it worked.

Opportunities are generated by the synthesis model, which makes them the softest
artefact in the pipeline -- so the constraints are tighter than anywhere else:

* Each one must name a **root-cause hypothesis it addresses**, chosen from the
  ones Phase 6 actually validated. An opportunity floating free of a mechanism
  is a suggestion, and suggestions are cheap.
* Each must state a **primary metric already measured by this pipeline**, not
  an aspirational one. "Improve customer satisfaction" cannot be checked;
  "reduce escalation_rate for this pain point" can.
* Each must state what it would **cost the customer if wrong**. A change that
  cannot hurt anyone is usually a change that will not help either.

None of that makes an opportunity correct. It makes it checkable, which is the
most this layer can honestly offer.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Sequence

from pydantic import BaseModel, Field, ValidationError

from voc.providers import LLMProvider
from voc.rootcause import _extract_json

logger = logging.getLogger(__name__)

OPPORTUNITY_PROMPT_VERSION = "v1"

#: Opportunities requested per pain point. Beyond three the model starts
#: restating the same change at different scopes.
DEFAULT_OPPORTUNITIES = 2

MAX_OUTPUT_TOKENS = 1600

#: Openings that signal an unexamined proposal. Checked as prefixes because the
#: schema's minimum length already rejects a bare "none", so what actually
#: arrives is a padded version of the same non-answer.
NO_RISK_PREFIXES: tuple[str, ...] = (
    "none", "no risk", "n/a", "nothing", "no downside", "minimal risk",
    "there is no risk", "no significant risk",
)

#: Metrics this pipeline actually measures. An opportunity naming anything else
#: is rejected, because its success condition could never be evaluated.
MEASURABLE_METRICS: tuple[str, ...] = (
    "negative_share",
    "severe_share",
    "escalation_rate",
    "churn_share",
    "praise_share",
    "pain_point_volume",
)


class Opportunity(BaseModel):
    """One proposed change, tied to a mechanism and a measurable outcome."""

    model_config = {"extra": "forbid"}

    title: str = Field(min_length=5, max_length=120)
    change: str = Field(min_length=20, description="What specifically would be built or changed.")
    addresses_hypothesis: str = Field(
        min_length=10,
        description="Which root-cause hypothesis this attacks, quoted or paraphrased.",
    )
    primary_metric: str = Field(description=f"One of: {', '.join(MEASURABLE_METRICS)}")
    expected_direction: str = Field(description="'decrease' or 'increase'")
    risk_if_wrong: str = Field(
        min_length=10,
        description="What it costs customers if this is the wrong change.",
    )


class OpportunityResponse(BaseModel):
    model_config = {"extra": "forbid"}

    opportunities: list[Opportunity] = Field(default_factory=list)


@dataclass
class OpportunityIssue:
    pain_point: str
    kind: str
    detail: str


@dataclass
class OpportunityResult:
    pain_point: str
    product_area: str
    issue_type: str
    opportunities: list[Opportunity] = field(default_factory=list)
    issues: list[OpportunityIssue] = field(default_factory=list)
    usage: dict[str, int] = field(default_factory=dict)
    requests_made: int = 0


SYSTEM_PROMPT = """\
You are a product manager turning diagnosed problems into candidate work.

You will be given ONE pain point, its measured signal, and the validated
root-cause hypotheses for it. Propose up to {n} OPPORTUNITIES.

Rules, all binding:

1. Each opportunity must address one of the SUPPLIED hypotheses. Do not invent
   a new cause and solve that instead.
2. `change` must be specific enough to estimate. "Improve the support
   experience" is not; "route tickets mentioning a refund straight to a human
   queue, skipping the bot" is.
3. `primary_metric` MUST be exactly one of: {metrics}
   These are the only outcomes this pipeline measures. Do not invent a metric.
4. `expected_direction` is "decrease" or "increase" -- which way the metric
   should move if the change works.
5. `risk_if_wrong` must name a concrete cost to customers. A change that cannot
   hurt anyone usually cannot help either, and saying "no risk" means the
   opportunity has not been thought through.

Do NOT estimate effort, cost, or timelines. You cannot see the codebase, and a
guess there would be treated as an estimate by whoever reads it.

Return JSON only:
{{"opportunities": [{{"title": "...", "change": "...",
  "addresses_hypothesis": "...", "primary_metric": "...",
  "expected_direction": "decrease", "risk_if_wrong": "..."}}]}}
"""


def build_system_prompt(n: int = DEFAULT_OPPORTUNITIES) -> str:
    return SYSTEM_PROMPT.format(n=n, metrics=", ".join(MEASURABLE_METRICS))


def build_user_message(
    product_area: str,
    issue_type: str,
    stats: dict[str, Any],
    hypotheses: Sequence[dict[str, Any]],
) -> str:
    lines = [
        f"PAIN POINT: {product_area} / {issue_type}",
        "",
        "Measured signal:",
        f"  reviews raising it     : {stats.get('volume', 'unknown')}",
        f"  mean severity          : {stats.get('mean_severity', 'unknown')} (low=1, critical=4)",
        f"  drove support contact  : {_percent(stats.get('escalation_rate'))}",
        f"  stated intent to leave : {_percent(stats.get('churn_rate'))}",
        "",
        f"VALIDATED ROOT-CAUSE HYPOTHESES ({len(hypotheses)}):",
        "",
    ]
    for n, item in enumerate(hypotheses, start=1):
        lines.append(f"{n}. {item.get('hypothesis', '')}")
        lines.append(f"   Mechanism: {item.get('mechanism', '')}")
        if item.get("disconfirming_evidence"):
            lines.append(f"   Against it: {item['disconfirming_evidence']}")
        lines.append("")
    return "\n".join(lines)


def _percent(value: Any) -> str:
    return f"{float(value) * 100:.0f}%" if isinstance(value, (int, float)) else "unknown"


def build_response_schema(n: int = DEFAULT_OPPORTUNITIES) -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "opportunities": {
                "type": "array",
                "maxItems": n,
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "change": {"type": "string"},
                        "addresses_hypothesis": {"type": "string"},
                        "primary_metric": {"type": "string", "enum": list(MEASURABLE_METRICS)},
                        "expected_direction": {"type": "string", "enum": ["decrease", "increase"]},
                        "risk_if_wrong": {"type": "string"},
                    },
                    "required": [
                        "title", "change", "addresses_hypothesis",
                        "primary_metric", "expected_direction", "risk_if_wrong",
                    ],
                    "additionalProperties": False,
                },
            }
        },
        "required": ["opportunities"],
        "additionalProperties": False,
    }


def validate_opportunities(
    items: Sequence[Opportunity], pain_point: str
) -> tuple[list[Opportunity], list[OpportunityIssue]]:
    """Reject opportunities whose success could never be evaluated."""
    kept: list[Opportunity] = []
    issues: list[OpportunityIssue] = []

    for item in items:
        if item.primary_metric not in MEASURABLE_METRICS:
            issues.append(
                OpportunityIssue(
                    pain_point, "unmeasurable_metric",
                    f"{item.primary_metric!r} is not measured by this pipeline: {item.title}",
                )
            )
            continue
        if item.expected_direction not in ("decrease", "increase"):
            issues.append(
                OpportunityIssue(
                    pain_point, "bad_direction",
                    f"{item.expected_direction!r} for {item.title}",
                )
            )
            continue
        # "No risk" is the tell for an unexamined proposal. Matched by prefix
        # rather than equality: the schema's min_length already blocks a bare
        # "none", so an equality check here could never fire, and the phrasing
        # that actually arrives is "No risk to customers."
        normalised = item.risk_if_wrong.strip().lower().rstrip(".")
        if any(normalised.startswith(prefix) for prefix in NO_RISK_PREFIXES):
            issues.append(
                OpportunityIssue(pain_point, "no_stated_risk", item.title)
            )
            continue
        kept.append(item)

    return kept, issues


def parse_response(text: str, pain_point: str) -> OpportunityResult:
    area, _, issue = pain_point.partition("/")
    result = OpportunityResult(
        pain_point=pain_point, product_area=area.strip(), issue_type=issue.strip()
    )

    payload = _extract_json(text)
    if payload is None:
        result.issues.append(OpportunityIssue(pain_point, "unparseable_response", text[:200]))
        return result
    if isinstance(payload, list):
        payload = {"opportunities": payload}

    try:
        parsed = OpportunityResponse(**payload)
    except ValidationError as exc:
        result.issues.append(OpportunityIssue(pain_point, "schema_violation", str(exc)[:200]))
        return result

    kept, issues = validate_opportunities(parsed.opportunities, pain_point)
    result.opportunities = kept
    result.issues.extend(issues)
    return result


def generate_opportunities(
    product_area: str,
    issue_type: str,
    stats: dict[str, Any],
    hypotheses: Sequence[dict[str, Any]],
    profile: Any,
    provider: LLMProvider,
    n: int = DEFAULT_OPPORTUNITIES,
) -> OpportunityResult:
    """Propose changes for one pain point. Never raises on a bad response."""
    pain_point = f"{product_area} / {issue_type}"

    if not hypotheses:
        return OpportunityResult(
            pain_point=pain_point,
            product_area=product_area,
            issue_type=issue_type,
            issues=[
                OpportunityIssue(
                    pain_point, "no_hypotheses",
                    "no validated root cause to build on; opportunities here would "
                    "be guesses dressed as analysis",
                )
            ],
        )

    try:
        completion = provider.complete(
            profile,
            build_system_prompt(n),
            build_user_message(product_area, issue_type, stats, hypotheses),
            build_response_schema(n),
            max_tokens=MAX_OUTPUT_TOKENS,
        )
    except Exception as exc:  # noqa: BLE001 - recorded, run continues
        logger.error("Opportunity request failed for %s: %s", pain_point, exc)
        return OpportunityResult(
            pain_point=pain_point,
            product_area=product_area,
            issue_type=issue_type,
            issues=[OpportunityIssue(pain_point, "api_error", str(exc)[:200])],
        )

    result = parse_response(completion.text, pain_point)
    result.product_area = product_area
    result.issue_type = issue_type
    result.requests_made = 1
    result.usage = dict(completion.usage or {})
    return result
