"""
Layer 3 (part 1) -- Reproducible data profiling.

Regenerates the dataset profile as a Markdown report from the immutable raw
file. Every number quoted in the README or in an interview should be traceable
to a run of this module rather than to a one-off notebook cell that no longer
exists.

Reads raw data only; writes nothing except the report.
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone

import pandas as pd

from voc.clean import (
    detect_truncation,
    ends_without_terminal_punct,
    has_non_latin,
    normalize_whitespace,
    parse_review_date,
)
from voc.schemas import COMPARABLE_WINDOW_START, PLATFORMS


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    """Render a GitHub-flavoured Markdown table."""
    head = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join("---" for _ in headers) + " |"
    body = "\n".join("| " + " | ".join(cells) + " |" for cells in rows)
    return "\n".join([head, sep, body])


def _percentile(values: list[int], fraction: float) -> int:
    ordered = sorted(values)
    return ordered[min(int(len(ordered) * fraction), len(ordered) - 1)]


def build_profile_report(
    raw: pd.DataFrame,
    *,
    source_path: str,
    checksum: str,
    source_bytes: int,
    truncation_cap_chars: int,
    truncation_tolerance: int,
) -> str:
    """Produce the full Markdown profile for the raw dataset."""
    total = len(raw)
    parts: list[str] = []

    # ---------------------------------------------------------------- header
    parts.append("# Data Profile — Raw Dataset\n")
    parts.append(
        "> Generated by `scripts/00_profile_data.py`. Reads the immutable raw file "
        "only. Re-run after any change to the source data.\n"
    )
    parts.append(
        _md_table(
            ["Property", "Value"],
            [
                ["Source", f"`{source_path}`"],
                ["SHA-256", f"`{checksum}`"],
                ["Size", f"{source_bytes:,} bytes"],
                ["Records", f"**{total:,}**"],
                ["Columns", str(raw.shape[1])],
                [
                    "Profiled at",
                    datetime.now(timezone.utc).isoformat(timespec="seconds") + " UTC",
                ],
            ],
        )
    )

    # ------------------------------------------------------- columns / types
    parts.append("\n## 1. Columns and completeness\n")
    rows = []
    for column in raw.columns:
        series = raw[column].astype(str)
        blanks = int((series.str.strip() == "").sum())
        sentinels = int(
            series.str.strip().str.lower().isin(["nan", "null", "none", "na", "n/a"]).sum()
        )
        rows.append(
            [
                f"`{column}`",
                str(series.nunique()),
                str(blanks),
                str(sentinels),
                f"{blanks + sentinels}",
            ]
        )
    parts.append(
        _md_table(["Column", "Distinct", "Blank", "Sentinel-like", "Total missing"], rows)
    )

    # --------------------------------------------------------------- ratings
    parts.append("\n## 2. Rating distribution\n")
    ratings = raw["rating"].astype(int)
    counts = ratings.value_counts().sort_index()
    rows = [
        [f"{star}★", f"{count:,}", f"{count / total * 100:.1f}%"]
        for star, count in counts.items()
    ]
    parts.append(_md_table(["Rating", "Count", "Share"], rows))
    negative = int((ratings <= 2).sum())
    positive = int((ratings >= 4).sum())
    parts.append(
        f"\nMean rating **{ratings.mean():.2f}**. "
        f"Negative (1–2★) **{negative / total * 100:.1f}%**, "
        f"positive (4–5★) **{positive / total * 100:.1f}%**.\n"
    )
    parts.append(
        "> **Sampling caveat.** This distribution is far more negative than a "
        "real user base. Treat the dataset as a complaint-biased sample: it is "
        "well suited to *finding problems*, and unsuitable for measuring "
        "satisfaction or ranking platforms by how happy their customers are.\n"
    )

    # -------------------------------------------------------------- platform
    parts.append("\n## 3. Platform distribution\n")
    rows = []
    for platform in PLATFORMS:
        subset = raw[raw["platform"].str.strip().str.lower() == platform]
        if subset.empty:
            continue
        subset_ratings = subset["rating"].astype(int)
        rows.append(
            [
                platform,
                f"{len(subset):,}",
                f"{len(subset) / total * 100:.1f}%",
                f"{subset_ratings.mean():.2f}",
                f"{(subset_ratings <= 2).mean() * 100:.1f}%",
                f"{(subset_ratings >= 4).mean() * 100:.1f}%",
            ]
        )
    parts.append(
        _md_table(
            ["Platform", "Reviews", "Share", "Mean rating", "% neg (1–2★)", "% pos (4–5★)"],
            rows,
        )
    )
    parts.append(
        "\n> **Do not read the rating gap as a satisfaction gap.** It tracks how "
        "each platform's reviews were collected, not how its customers feel.\n"
    )

    # ------------------------------------------------------------- date span
    parts.append("\n## 4. Date coverage\n")
    dates = raw["date"].map(parse_review_date)
    platforms_lower = raw["platform"].str.strip().str.lower()
    parts.append(
        f"Span **{dates.min()} → {dates.max()}** "
        f"({(dates.max() - dates.min()).days:,} days).\n"
    )

    year_month = dates.map(lambda d: f"{d.year}-{d.month:02d}")
    monthly = Counter(year_month)
    recent_months = sorted(monthly)[-8:]
    rows = []
    for month in recent_months:
        mask = year_month == month
        per_platform = Counter(platforms_lower[mask])
        rows.append(
            [month]
            + [f"{per_platform.get(p, 0):,}" for p in PLATFORMS]
            + [f"{int(mask.sum()):,}"]
        )
    parts.append(_md_table(["Month", *PLATFORMS, "Total"], rows))

    in_window = int((dates >= COMPARABLE_WINDOW_START).sum())
    parts.append(
        f"\n**{in_window:,} of {total:,} reviews ({in_window / total * 100:.1f}%)** fall on or "
        f"after `{COMPARABLE_WINDOW_START}`, the point from which all three platforms "
        "are meaningfully present.\n\n"
        "> **Trend-analysis ceiling.** Only three monthly buckets support "
        "cross-platform comparison. That rules out seasonality, year-over-year, "
        "and statistical spike detection. Trends must be reported as *share* "
        "changes, never raw counts — the negative share itself drifts month to "
        "month, so counts would measure scrape composition rather than customer "
        "experience.\n"
    )

    # ------------------------------------------------------------------ text
    parts.append("\n## 5. Review text\n")
    normalised = raw["review"].map(normalize_whitespace)
    lengths = normalised.str.len().tolist()
    words = normalised.str.split().str.len().tolist()
    parts.append(
        _md_table(
            ["Metric", "min", "p10", "p50", "p90", "p99", "max"],
            [
                ["Characters"]
                + [
                    str(v)
                    for v in (
                        min(lengths),
                        _percentile(lengths, 0.10),
                        _percentile(lengths, 0.50),
                        _percentile(lengths, 0.90),
                        _percentile(lengths, 0.99),
                        max(lengths),
                    )
                ],
                ["Words"]
                + [
                    str(v)
                    for v in (
                        min(words),
                        _percentile(words, 0.10),
                        _percentile(words, 0.50),
                        _percentile(words, 0.90),
                        _percentile(words, 0.99),
                        max(words),
                    )
                ],
            ],
        )
    )

    # Evidence for the truncation cap: show the pile-up at the ceiling.
    length_counter = Counter(lengths)
    bands = [(440, 460), (460, 480), (480, 500), (500, 501)]
    rows = [
        [
            f"{low}–{high - 1}" if high - low > 1 else f"exactly {low}",
            f"{sum(count for length, count in length_counter.items() if low <= length < high):,}",
        ]
        for low, high in bands
    ]
    parts.append("\n### Truncation evidence\n")
    parts.append(_md_table(["Character band", "Reviews"], rows))
    truncated = sum(
        1
        for length in lengths
        if detect_truncation("x" * length, truncation_cap_chars, truncation_tolerance)
    )
    parts.append(
        f"\n**{truncated:,} reviews ({truncated / total * 100:.1f}%)** sit within "
        f"{truncation_tolerance} characters of the {truncation_cap_chars}-character ceiling. "
        "The pile-up at the top band against the thinner bands below it is the "
        "signature of a scraper cap, not of natural writing length. Truncated "
        "reviews can lose their resolution clause, biasing sentiment negative.\n"
    )

    # ------------------------------------------------------- quality summary
    parts.append("\n## 6. Data-quality flags\n")
    whitespace_affected = int((raw["review"] != normalised).sum())
    no_terminal = int(normalised.map(ends_without_terminal_punct).sum())
    non_latin = int(normalised.map(has_non_latin).sum())
    exact_dupes = int(normalised.str.lower().duplicated().sum())
    parts.append(
        _md_table(
            ["Check", "Count", "Share", "Handling"],
            [
                [
                    "Whitespace/newline padding",
                    f"{whitespace_affected:,}",
                    f"{whitespace_affected / total * 100:.1f}%",
                    "Normalised in cleaning",
                ],
                [
                    "At truncation ceiling",
                    f"{truncated:,}",
                    f"{truncated / total * 100:.1f}%",
                    "Flagged `is_truncated`",
                ],
                [
                    "No terminal punctuation",
                    f"{no_terminal:,}",
                    f"{no_terminal / total * 100:.1f}%",
                    "Flagged",
                ],
                [
                    "Exact duplicate text",
                    f"{exact_dupes:,}",
                    f"{exact_dupes / total * 100:.1f}%",
                    "Flagged, not dropped",
                ],
                [
                    "Non-Latin script present",
                    f"{non_latin:,}",
                    f"{non_latin / total * 100:.1f}%",
                    "Flagged; multi-language out of scope",
                ],
            ],
        )
    )

    parts.append("\n## 7. Known limitations of this dataset\n")
    parts.append(
        "- **Complaint-biased sample.** Not representative of the user base. "
        "Every downstream claim must be scoped *within this review dataset*.\n"
        "- **Platform rating gaps are confounded** with how each platform's "
        "reviews were collected. Cross-platform *satisfaction* ranking is not "
        "supported and is deliberately not offered by the product.\n"
        "- **Three usable trend buckets.** No seasonality or year-over-year.\n"
        "- **No identifiers in source.** No user ID (repeat reviewers are "
        "invisible), no app version, city, or order value — so root-cause "
        "output is limited to *hypotheses* from text, never confirmed causes.\n"
        "- **App-store-shaped feedback.** Reviews mix app bugs with operational "
        "failures and cannot be tied to specific orders or SKUs.\n"
    )

    return "\n".join(parts) + "\n"
